### PR TITLE
feat：feat custom localstorage system config

### PR DESCRIPTION
**Pull request by HardenSG**
feat：
1. feat custom localstorage system config
2. feat all wallpaper by useSystemConfig store
3. feat env file and project config file and i can set my own configuration for this software

Bad trouble：
When I commit these code, I'm having some trouble, a Assertion Error, and the detail info is "AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided"
Through search engine query, i realized that this may be a nuisance caused by enumeration. right, and that's exactly what happened. so i mark this flag in code: "/* eslint-disable no-unused-vars */", the trouble was solved

### CODE REVIEW

**Comment by SG-Good-Night** [comment]
> feat：
> 
> 1. feat custom localstorage system config
> 2. feat all wallpaper by useSystemConfig store
> 3. feat env file and project config file and i can set my own configuration for this software
> 
> Bad trouble： When I commit these code, I'm having some trouble, a Assertion Error, and the detail info is "AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided" Through search engine query, i realized that this may be a nuisance caused by enumeration. right, and that's exactly what happened. so i mark this flag in code: "/* eslint-disable no-unused-vars */", the trouble was solved

so cool

**Review by SG-Good-Night — COMMENTED** [review]
that's right

**Review by SG-Good-Night — APPROVED** [review]
ok, i'll merge it

**Comment by HardenSG** [comment]
> ok, i'll merge it

thanks, my bro

**Pull request merged**
